
import Image from "next/image"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Chipeadoras - EcoAlliance",
    description: "Generated by create next app",
  };



const ProductoGeneral = () =>{
    return(
        <main>
            {/* <section>
                 <Image src="/chipeadora/banner_principal.png" alt="Banner Chipeadoras" width={2000} height={200} />
            </section> */}

            <section className="mb-20">
                <div className="mt-20">
                    <p className="text-center text-sm">Responde esta pregunta y encuentra la chipeadora ideal para ti.</p>
                    <h2 className="text-center text-2xl mt-2">¿Buscas una chipeadora para podas domésticas o para <br/> procesamiento continuo en grandes proyectos?</h2>   
                </div>
                <div className="md:flex mt-20 px-14 xl:px-52 border shadow-xl pb-10">

                    <div className="w-full md:w-1/2 lg:w-1/3 flex items-center">
                        <div>
                            <div className="flex justify-center">
                                <Image src="/chipeadora/chipeadora_elliet.png" alt="Banner Chipeadoras" width={200} height={200} />
                            </div>
                            <p className="text-center">Chipeadoras portátiles ideales para poda y mantenimiento en el hogar o áreas verdes pequeñas, diseñadas para necesidades básicas de limpieza.</p>
                            <div className="flex justify-center mt-5">
                                <a href={"/chipeadoras/eliet"} className="bg-black text-white py-2 px-7 rounded-full">Ir a Chipeadoras Eliet</a>
                            </div>
                        </div>
                    </div>

                    <div className="hidden lg:block w-1/3 ">
                        <Image src="/chipeadora/hojas.png" alt="Banner Chipeadoras" width={500} height={200} />
                    </div>
                    <div className="w-full md:w-1/2 lg:w-1/3 flex items-center">
                        <div>
                            <div className="flex justify-center">
                                <Image src="/chipeadora/chipeadora_jensen.png" alt="Banner Chipeadoras" width={250} height={250} />

                            </div>
                            <p className="text-center">Chipeadoras ideales para aplicaciones de gran escala como agricultura y paisajismo, diseñadas para manejar grandes volúmenes de poda con eficiencia y resistencia.</p>
                            <div className="flex justify-center mt-5">
                                <a href={"/chipeadoras/jensen"} className="bg-black text-white py-2 px-7 rounded-full">Ir a Chipeadoras Jensen</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

       
        </main>
    )

}

export default ProductoGeneral